#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrandr -s 1366x768 &
picom &
#polybar example &
tint2 &

setxkbmap latam &

#Fondo
feh --bg-fill /home/hatsu/Imágenes/fondos/fondo1.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
